### PR TITLE
User Creation

### PR DESCRIPTION
**Pull request by BrianCravens**

### CODE REVIEW

**Comment by ZachNich** [comment]
looks like Uncaught ReferenceError: displayWelcome is not defined
    at main.js:6

**Comment by ZachNich** [comment]
Looks good this time! I would recommend adding validation to the email when creating a user, so we don't have multiple emails in the database (like you have for duplicate usernames). Otherwise looks good! We may also want to require usernames and passwords to be x length, or to make sure emails have the xxx@xxx.xx format

**Comment by ZachNich** [comment]
👍

**Review by mbrownlee — APPROVED** [review]
Looks good.

**Pull request merged**
