### PR TITLE
Bc news

### PR DESCRIPTION
**Pull request by BrianCravens**

### CODE REVIEW

**Comment by ZachNich** [comment]
Need to merge or discard changes in index.html. Hard to replicate, but sometimes when I edited an entry, it would not edit. Most times, it would. If anyone else can replicate that error, we should try to fix it.

**Comment by tstrotherIV** [comment]
can create articles, can edit articles
👍

**Comment by mbrownlee** [comment]
:shipit:

**Comment by ZachNich** [comment]
👍

**Pull request merged**
